version: '3.8'

services:
  postgredb:
    build:
      context: ./requirements/PostgreSQL
    env_file:
      - .env
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    networks:
      - transcendence 

secrets:
  postgres_password:
    file: ../secret/postgres_password # Emplacement du fichier de secret

networks:
  transcendence:
