# Generated by Django 5.1.4 on 2025-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0002_remove_signupuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/'),
        ),
    ]
