# Generated by Django 4.2.19 on 2025-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0010_signupuser_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
