version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.18.2
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"  # Utilisé uniquement en mode dev
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK  # Ajout de la capacité IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - vault_data:/vault/file
    networks:
      - app-network
    command: ["server", "-dev", "-dev-root-token-id=root"]

  backend:
    image: crccheck/hello-world
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  mod:
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: mod:latest
    container_name: mod
    depends_on:
      - backend
      - vault
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    networks:
      - app-network
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"  # Utilisé uniquement en mode dev

networks:
  app-network:
    driver: bridge

volumes:
  vault_data:
