# Generated by Django 5.1.4 on 2025-01-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0003_signupuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='profile_picture',
        ),
    ]
