# Generated by Django 5.1.4 on 2025-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0005_signupuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
