# Generated by Django 5.1.4 on 2025-01-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0006_alter_signupuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
