# Generated by Django 5.1.4 on 2025-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0008_signupuser_otp_code_signupuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
