# Fichier : modsecurity.conf
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
# SecRequestBodyInMemoryLimit 131072
SecPcreMatchLimit 100000
SecPcreMatchLimitRecursion 100000

SecRule REQUEST_HEADERS:User-Agent ".*" "id:1002,phase:1,pass,t:none,setvar:ip.req_count=+1"
SecRule IP:REQ_COUNT "@ge 10000" "id:1003,phase:1,deny,log,msg:'Too many requests from IP'"


# Inclure les règles OWASP CRS
Include /etc/nginx/modsec-coreruleset/crs-setup.conf
Include /etc/nginx/modsec-coreruleset/rules/*.conf
