# Generated by Django 5.1.4 on 2025-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0007_alter_signupuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='signupuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
